### PR TITLE
cleanup of entrypoint.sh

### PR DESCRIPTION
**Pull request by mustaphazorgati**
Hey @rokroskar!

Thank you for your quick responses. In order to increase maintainability I've cleaned up the code a little bit. What do you think?

### CODE REVIEW

**Comment by rokroskar** [comment]
I believe you might have a problem with a rebase here - the `|| :` is missing from Line 31

**Comment by mustaphazorgati** [comment]
> I believe you might have a problem with a rebase here - the `|| :` is missing from Line 31

Since I've created this PR before the fix today it's not included. But it doesn't matter since a merge will combine both changes ;)

**Comment by mustaphazorgati** [comment]
If you insist I will rebase.

**Comment by mustaphazorgati** [comment]
> I believe you might have a problem with a rebase here - the `|| :` is missing from Line 31

I would have a merge conflict if I'd have modified that line. But I didn't. So we're good :)

**Comment by rokroskar** [comment]
Ah nevermind, it's not insisting on the branch being up-to-date because there are no checks running. That's why there is no "update branch" button. All good!

**Comment by mustaphazorgati** [comment]
Alright! What do you think about the change? After the mishap today I had a second look and tested this again to make sure that it's not breaking.

**Comment by mustaphazorgati** [comment]
Hey @rokroskar,

sorry. I have closed this PR by accident. I re-opened it again so that you can merge it ;)

**Comment by mustaphazorgati** [comment]
reposted as #23

**Pull request closed without merging**
