### PR TITLE
chore: refactor variable naming

### LINKED ISSUE #26: Cleanup: Replace current way of creating variables with more expressive way
Currently we use the function `exportAll` to declare our needed variables at runtime. According to shellcheck this is not good.

Please replace the way of creating those variables with a more traditional way and unmute all shellcheck warnings according this issue.

### PR DESCRIPTION
**Pull request by mustaphazorgati**
closes #26

### CODE REVIEW

**Comment by mustaphazorgati** [comment]
Hey @rokroskar,

rebased ;)

**Comment by mustaphazorgati** [comment]
Hey @rokroskar,
I guess you didn't look at this. Too busy, or just didn't notice? :)

**Comment by rokroskar** [comment]
Sorry @mustaphazorgati been super busy - it should let up a bit after today and I can have a look later this week.

**Comment by mustaphazorgati** [comment]
Hey @rokroskar,
no worries. This is a low priority ticket :)

**Comment by mustaphazorgati** [comment]
Hey mate!
It has been a while. Did you forget this one? :D

**Comment by mustaphazorgati** [comment]
@rokroskar bump ;)

**Review by rokroskar — APPROVED** [review]
Thanks @mustaphazorgati! Sorry that took a while... 🙈

**Comment by mustaphazorgati** [comment]
No worries mate :) I hope I was not too intrusive

**Comment by rokroskar** [comment]
Not at all, thanks for the contribution!

**Pull request merged**
